id: kotlin
name: Kotlin
shortName: Kt
aliases: [kt, kotlin-jvm]
version: '2.1'
fileExtension: .kt
comment:
  line: '//'
  block: ['/*', '*/']
shikiLang: kotlin
paradigm: [oop, functional, multi-paradigm]
typing: static
typeSystem: nominal
memoryModel: gc
concurrency: [coroutines, threads, flows]
baseline: false
links:
  - label: Kotlin 官方文档
    url: https://kotlinlang.org/docs/home.html
