id: dart
name: Dart
shortName: Dart
aliases: [flutter-dart]
version: '3.6'
fileExtension: .dart
comment:
  line: '//'
  block: ['/*', '*/']
shikiLang: dart
paradigm: [oop, functional, multi-paradigm]
typing: static
typeSystem: nominal
memoryModel: gc
concurrency: [event-loop, isolate, async-await]
baseline: false
links:
  - label: Dart 官方语言之旅
    url: https://dart.dev/language
